#ifndef SHAREDTYPES_H
#define SHAREDTYPES_H

enum SourceType {VIDEO = 1, IMAGES = 2};
enum TrackType {SNAKE = 1};
enum States {UNINITIALIZED = 0, VIDEO_LOADED, ABNORMALRANGE_SELECTED, CONF_FINISHED, TRUTH_GENERATED, TRUTH_SAVED};

#endif // SHAREDTYPES_H
